[litex]
github_user = "enjoy-digital"
github_repo = "litex"
git_revision = "a3309c3510e647e2e9e6380d18774a30bf48849d"
github_archive_nix_hash = "jBGxPwM8bWf+cJOSiTVDFzI5gh5ByIEdt+BlCjK8ock="

[litex-boards]
github_user = "litex-hub"
github_repo = "litex-boards"
git_revision = "7a5ec73e606911c18d82545c0ed925b41536195a"
github_archive_nix_hash = "0y5v1kyq7vildrx8c7278dvc33gqxnida9c5q2mkfh6x0y2g37s8"

[liteeth]
github_user = "enjoy-digital"
github_repo = "liteeth"
git_revision = "f43188d81cd8f9639a75bed2729bcd8f4e708bd5"
github_archive_nix_hash = "ezBIHGp2YjpA0Ob8HtyrCDHbCA3+00x40vJf7ByHsEY="

[litedram]
github_user = "enjoy-digital"
github_repo = "litedram"
git_revision = "dd85a5744d0ed0c359c4d3d82151fe69ca7b8632"
github_archive_nix_hash = "+IHy2g5mGnZmLVfa9X7Lp37qO5UvdL8JCJKeqZDNV5s="

[litehyperbus]
github_user = "litex-hub"
github_repo = "litehyperbus"
git_revision = "0ed04c58e0fac25aa7109adb065b118a9d457e9e"
github_archive_nix_hash = "00bjj4az4dw8zjac9fwvmhmfxrj84x2d8zlyw1v4vy05s1rfivax"

[liteiclink]
github_user = "enjoy-digital"
github_repo = "liteiclink"
git_revision = "3d8ecdbcf9f026"
github_archive_nix_hash = "0blvgg26pf174nl8gi91a3aahalav0l4fcqdyphhc2i49iz63rnr"

[litepcie]
github_user = "enjoy-digital"
github_repo = "litepcie"
git_revision = "c06d3529aa55033c181bfc36ae8fe05f4c362ebb"
github_archive_nix_hash = "1l9jxm10171cxjmyd887ng158kalk6a384cra6n90s5ph0g3fxpx"

[litescope]
github_user = "enjoy-digital"
github_repo = "litescope"
git_revision = "5dd5fa6ce3a996d5e667559c386fe5c60bc0dc6e"
github_archive_nix_hash = "5/5WATOBllb0wXVfTPtkivdWCzwQCK9ijGsbCBk4Q4Q="

[litesdcard]
github_user = "enjoy-digital"
github_repo = "litesdcard"
git_revision = "4edf05e627a8b5f03e632215accec8ab588737e3"
github_archive_nix_hash = "IfD6wYT3+b/bY+LwktDIrcO+kbbVi+oeHeK3Qiitcbw="

[litespi]
github_user = "litex-hub"
github_repo = "litespi"
git_revision = "e7612d0e6ea54be4d561f633aafc140729c9142f"
github_archive_nix_hash = "01d1vjb749p2zrrs2j158f4i5c82377dvpv0rblr6xvv3qbnq48p"

[pythondata-cpu-vexriscv]
version = "2021030800"
tarball_url = "https://github.com/lschuermann/litex-vexriscv-custom/releases/download/2021030800/generated.tar.gz"

[pythondata-misc-tapcfg]
github_user = "litex-hub"
github_repo = "pythondata-misc-tapcfg"
git_revision = "0e6809132b7a42"
github_archive_nix_hash = "182m452iclahx1ipic0x7q4c9w33w6vfm9lz8zbx39zli9dg7l03"

[pythondata-software-compiler_rt]
github_user = "litex-hub"
github_repo = "pythondata-software-compiler_rt"
git_revision = "0492a56763ffc947feaee2dcf7e7e3393d3407b6"
github_archive_nix_hash = "06pz4zs8wizx1yp5sv07l9gs71brlr4c8jrxszp0jq7h2g35zyxk"

[pythondata-cpu-serv]
github_user = "litex-hub"
github_repo = "pythondata-cpu-serv"
git_revision = "da5ad1e992e1a6"
github_archive_nix_hash = "sha256:0awqylqj11nkzashk3wlbjl8d8lx7a3lxaa304jrbgn6zr13x1xx"
